version: 0.0
os: linux
files:
  - source: api/cs415/
    destination: /home/ubuntu/cs415_api/

file_exists_behavior: OVERWRITE

# Hooks:
#   - BeforeInstall: scripts/start_apps.sh
#   - AfterInstall: scripts/stop_apps.sh